site_name: Belajar Go (Golang)
site_description: Panduan project-based belajar Go untuk menjadi programmer tangguh.
site_author: Lalu Wahyudi
site_url: https://kodinggratis.github.io/go

theme:
  name: readthedocs
  custom_dir: overrides

nav:
  - Get Started: index.md
  - Panduan Belajar: panduan.md
  - Daftar Isi: daftar-isi.md
  - Fase I Pondasi:
      - 1.1 Sintaksis & Tipe data:
          - 1.1.1 Tipe Data Primitif:
              - 1.1.1.1 Integer Types: sintaksis-dan-tipe-data/tipe-data-primitif/integer.md
              - 1.1.1.2 Floating Types: sintaksis-dan-tipe-data/tipe-data-primitif/float.md
              - 1.1.1.3 Complex Types: sintaksis-dan-tipe-data/tipe-data-primitif/complex.md
              - 1.1.1.4 Boolean: sintaksis-dan-tipe-data/tipe-data-primitif/boolean.md
              - 1.1.1.5 String: sintaksis-dan-tipe-data/tipe-data-primitif/string.md
              - 1.1.1.6 Type Conversion & Assertion: sintaksis-dan-tipe-data/tipe-data-primitif/conversion-assertion.md
              - 1.1.1.7 Zero Values: sintaksis-dan-tipe-data/tipe-data-primitif/zero-values.md
          - 1.1.2 String Manipulation:
              - 1.1.2.1 String Immutability: sintaksis-dan-tipe-data/control-flow/string-immutability.md
              - 1.1.2.2 Rune Vs Byte: sintaksis-dan-tipe-data/control-flow/rune-byte.md
              - 1.1.2.3 UTF-8 Encoding: sintaksis-dan-tipe-data/control-flow/utf8-encoding.md
              - 1.1.2.4 Package String & strconv: sintaksis-dan-tipe-data/control-flow/package-string-strconv.md
              - 1.1.2.5 String Interpolation & Formating (fmt): sintaksis-dan-tipe-data/control-flow/string-interpolation-formatting.md
          - 1.1.3 Constants & Variable:
              - 1.1.3.1 Var vs := (Short Declaration): sintaksis-dan-tipe-data/constants-variable/var-short-declaration.md
              - 1.1.3.2 Const & iota: sintaksis-dan-tipe-data/constants-variable/const-iota.md
              - 1.1.3.3 Typed vs Untyped Constans: sintaksis-dan-tipe-data/constants-variable/typed-untyped-constants.md
              - 1.1.3.4 Variable Shadowing: sintaksis-dan-tipe-data/constants-variable/variable-shadowing.md
              - 1.1.3.5 Multiple Variable Declaration: sintaksis-dan-tipe-data/constants-variable/multiple-variable-declaration.md
      - Nice to Have:
          - Type Aliases Vs Type Definitions: nice-to-have/type-aliases-vs-type-definitions.md
          - Blank Identifier: nice-to-have/blank-identifier.md
          - Custom Type Creation: nice-to-have/custom-type-creation.md
          - Type Embedding Basic: nice-to-have/type-embedding-basic.md
      - Low Project:
          - Number Analyzer: low-project/fase-1/number-analyzer.md
          - String Inspector: low-project/fase-1/string-inspector.md
          - Temperature & Currency Converter CLI: low-project/fase-1/temperature-currency-converter-cli.md
          - Kalkulator CLI Multi-Operasi: low-project/fase-1/kalkulator-cli-multi-operasi.md
          - Password Strength Analyzer: low-project/fase-1/password-strength-analyzer.md
          - Mini Quiz CLI: low-project/fase-1/mini-quiz-cli.md
          - Data Formatter Utility: low-project/fase-1/data-formatter-utility.md
          - Sistem Kasir Mini: low-project/fase-1/sistem-kasir-mini.md
          - Validasi Formulir User: low-project/fase-1/validasi-formulir-user.md
          - Rating & Review Analyzer: low-project/fase-1/rating-review-analyzer.md
          - Validator Nama & Username: low-project/fase-1/validator-nama-username.md
          - Currency Formatter: low-project/fase-1/currency-formatter.md
          - Text Cleaner / Normalizer: low-project/fase-1/text-cleaner-normalizer.md
          - Login Attempt Limiter: low-project/fase-1/login-attempt-limiter.md

      - 1.2 Control Flow:
          - 1.2.1 Kondisi & Percabangan: low-project/building-web-scraper.md

  - Tentang: tentang.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - tables
  - footnotes

plugins:
  - search

extra_css:
  - styles/custom.css

copyright: >
  Â© 2025 Koding Gratis by Lalu Wahyudi. Dibuat dengan MkDocs dan semangat belajar terbuka.
